### ISSUE TITLE
No jupyterlab token, invalid credentials

### ISSUE THREAD

**Issue by stevenhurwitt** [edbullen/DockerSpark245#2]
Not really an issue with your repo, but i'm trying to set it up and jupyterlab docker container isn't giving me a token to set a password.

I tried adding this command to the jupyterlab.Dockerfile: 

`CMD jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --ServerApp.token='' --ServerApp.password=''`

but am getting "invalid credentials" with that.

Running `docker-compose logs` just shows this output with no token:

```
jupyterlab        | [I 2022-03-26 23:04:52.138 ServerApp] jupyterlab | extension was successfully linked.
jupyterlab        | [I 2022-03-26 23:04:52.146 ServerApp] nbclassic | extension was successfully linked.
jupyterlab        | [I 2022-03-26 23:04:52.148 ServerApp] Writing Jupyter server cookie secret to /root/.local/share/jupyter/runtime/jupyter_cookie_secret
jupyterlab        | [I 2022-03-26 23:04:52.313 ServerApp] notebook_shim | extension was successfully linked.
jupyterlab        | [W 2022-03-26 23:04:52.328 ServerApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
jupyterlab        | [I 2022-03-26 23:04:52.330 ServerApp] notebook_shim | extension was successfully loaded.
jupyterlab        | [I 2022-03-26 23:04:52.331 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.7/site-packages/jupyterlab
jupyterlab        | [I 2022-03-26 23:04:52.331 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
jupyterlab        | [I 2022-03-26 23:04:52.334 ServerApp] jupyterlab | extension was successfully loaded.
jupyterlab        | [I 2022-03-26 23:04:52.338 ServerApp] nbclassic | extension was successfully loaded.
jupyterlab        | [I 2022-03-26 23:04:52.339 ServerApp] Serving notebooks from local directory: /opt/workspace
jupyterlab        | [I 2022-03-26 23:04:52.339 ServerApp] Jupyter Server 1.15.6 is running at:
jupyterlab        | [I 2022-03-26 23:04:52.339 ServerApp] http://58317d169557:8888/lab
jupyterlab        | [I 2022-03-26 23:04:52.339 ServerApp]  or http://127.0.0.1:8888/lab
jupyterlab        | [I 2022-03-26 23:04:52.339 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

The other thing I tried was `docker exec -it jupyterlab bash` and then running `jupyter notebook list` but it doesn't show any running servers.

Did you experience this issue at all?

**Comment by stevenhurwitt** [comment]
also unrelated - how to resize spark master and worker memory and cores? do i have to set them in spark-defaults.conf?

**Comment by edbullen** [comment]
I don't know the answer to your question and I am not sure why this is important for a local environment?  Does Jupyter need to be secured for a local experiment zone on your laptop?  

In  answer to your second question - check the `SPARK_WORKER_CORES` and `SPARK_WORKER_MEMORY` in the Docker compose file.  These params can be set for the Spark worker memory and core config.

**Comment by edbullen** [comment]
Closing the issue - I don't think there is anything that affects the functionality here.

**Comment by stevenhurwitt** [comment]
I don't need jupyter secured, but it was a default setting with jupyter lab. on the off chance anyone needs it the solution was to add this to the `docker-compose.yaml`:

```
environment:
      - JUPYTER_TOKEN=easy
```
