### ISSUE TITLE
Help on Spark learn and usage

### ISSUE THREAD

**Issue by brunolnetto** [edbullen/DockerSpark245#4]
Hi @edbullen,

I try to understand the philosophy behind spark products. Your repository popped out to me as a suggestion to spark experiments. In the past, I cloned a repository with a similar architecture design [here](https://github.com/trouchet/sparkles). However, the data source was a local (table-)sheet, and I think I did not learn enough. Do you have any material or recommendations on where to start?

**Comment by edbullen** [comment]
Hi, basic philosophy behind Spark is distributed in-memory computing for data analytics.  Take a look at https://spark.apache.org/ for more detail.  If you clone this repo you will see some notebooks that will get you started and these reference this book which is great learning material: https://www.amazon.co.uk/Books-Matei-Zaharia/s?rh=n%3A266239%2Cp_27%3AMatei+Zaharia
